config/routes.rb
Mountwiki::Application.routes.draw do
  resources :continents
  resources :regions
  resources :mounts
  resources :routes

  match "/filter" => "routes#filter"
  match "/search" => "routes#search"
  match "/api/regions/" => "regions#api_regions"
  match "/api/mounts/" => "mounts#api_mounts"

  root :to => "routes#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :read, :all if user
    can :manage, :all if user.has_role? :admin

    can :manage, Route if user.has_role? :moderator
    can :manage, [Route, Mount, Region] if user.has_role? :moderator
    can :create, [Route, Mount, Region] if user.persisted?
    can [:edit, :update], [Route, Mount, Region] do |resource|
        user.persisted? && resource.user == user
    end
  end
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  attr_protected :secret
  
  has_many :regions 
  has_many :mounts, :through => :regions
  has_many :routes, :through => :mounts   
  #name
  
end

app/models/mount.rb
class Mount < ActiveRecord::Base
  #attr_accessible :description, :elevation, :title, :photo
  attr_protected :secret

  has_many :routes
  belongs_to :region

  mount_uploader :photo, PhotoUploader
end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_protected :secret

  belongs_to :continent
  belongs_to :user
  has_many :mounts 
  has_many :routes, :through => :mount

  #name
  #description
  #photo
  #has_many photos
  mount_uploader :photo, PhotoUploader
end

app/models/route.rb
class Route < ActiveRecord::Base
  attr_protected :secret
  belongs_to :mount
  belongs_to :region
  belongs_to :continent
  belongs_to :user

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  rolify

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  inherit_resources
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mounts_controller.rb
class MountsController < ApplicationController
  inherit_resources

  def api_mounts
    if params[:continent_id].present?
      render :json => Continent.find(params[:continent_id]).mounts.to_json
    elsif params[:region_id].present?
      render :json => Mount.where(region_id: params[:region_id]).all.to_json
    end
  end 
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  inherit_resources
  
  def api_regions
    render :json => Region.where(continent_id: params[:continent_id]).all.to_json
  end 
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  load_and_authorize_resource
  inherit_resources
  actions :all, :except => [ :index ]
  respond_to :json, :js, :html

  def index
    if params[:continent]
      continent = Continent.find params[:continent]
      @routes = continent.routes.all
    elsif params[:region]
      region = Region.find params[:region]
      @routes = region.routes.all
    elsif params[:mount]
      region = Mount.find params[:mount]
      @routes = mount.routes.all
    else
      @routes = Route.all
    end    
    render
  end

  def filter
    params[:route].each {|key, param| params[:route].delete(key) if param == "" }    
    @routes = Route.where(params[:route]).all
    render :layout => false 
  end

  def search
    @routes = Route.order(:title).where("name like ?", "%#{params[:query]}%") if params[:query].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/continents/_form.html.haml
= semantic_form_for @continent, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), mounts_path, :class => 'btn'

app/views/continents/edit.html.haml
- model_class = Continent
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/continents/index.html.haml
- model_class = Continent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @continents.each do |continent|
      %tr
        %td= link_to continent.id, continent_path(continent)
        %td= continent.title
        %td=l continent.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_continent_path(continent), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), continent_path(continent), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_continent_path, :class => 'btn btn-primary'

app/views/continents/new.html.haml
- model_class = Continent
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/continents/show.html.haml
- model_class = Continent
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @continent.title

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), continents_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_continent_path(@continent), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), continent_path(@continent), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/home/index.html.haml
= "Ого какой крутой проект"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Mountwiki"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .wrapper
      .container-fluid
        .span1.logo
          %a.brand(href="/") All_Routes
      .container-fluid.main_content
        .row-fluid
          .span3
            .well.sidebar-nav
              =render_cell :menu, :left
          .span9
            =render_cell :menu, :top  
            = yield    
    %footer
      -# render_cell :footer, :show
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/mounts/_form.html.haml
= semantic_form_for @mount, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :description
  = f.input :elevation
  = f.input :region
  = f.input :photo
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), mounts_path, :class => 'btn'

app/views/mounts/edit.html.haml
- model_class = Mount
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/mounts/index.html.haml
- model_class = Mount
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:elevation)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @mounts.each do |mount|
      %tr
        %td= link_to mount.id, mount_path(mount)
        %td= mount.title
        %td= mount.description
        %td= mount.elevation
        %td=l mount.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_mount_path(mount), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), mount_path(mount), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_mount_path, :class => 'btn btn-primary'

app/views/mounts/new.html.haml
- model_class = Mount
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/mounts/show.html.haml
- model_class = Mount
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @mount.title
%p
  %strong= model_class.human_attribute_name(:photo) + ':'
  %br
  = image_tag @mount.photo.medium.url

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @mount.description
%p
  %strong= model_class.human_attribute_name(:elevation) + ':'
  %br
  = @mount.elevation

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), mounts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_mount_path(@mount), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), mount_path(@mount), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/regions/_form.html.haml
= semantic_form_for @region, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :description
  = f.input :continent
  = f.input :photo
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), mounts_path, :class => 'btn'

app/views/regions/edit.html.haml
- model_class = Region
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/regions/index.html.haml
- model_class = Region
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:descripion)
      %th= model_class.human_attribute_name(:photo)
      %th= model_class.human_attribute_name(:continent_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @regions.each do |region|
      %tr
        %td= link_to region.id, region_path(region)
        %td= region.title
        %td= region.description
        %td= region.photo
        %td= region.continent_id
        %td=l region.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_region_path(region), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), region_path(region), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_region_path, :class => 'btn btn-primary'

app/views/regions/new.html.haml
- model_class = Region
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/regions/show.html.haml
%h1= @region.title
- if can? :edit, @region
  = link_to "Редактировать", edit_region_path(@region) 
%p  
  = image_tag @region.photo.url

%h3= "Описание."
%p= @region.description

app/views/routes/_form.html.haml
= semantic_form_for @route, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :description
  = f.input :difficulty
  = f.input :continent
  = f.input :region
  = f.input :mount
  = f.input :photo
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), mounts_path, :class => 'btn'

app/views/routes/_routes_list.html.haml
- routes.each do |route|
  .row-fluid.route_list_item
    .span1= image_tag route.photo.thumb.url
    .span6
      = link_to "#{route.mount.title} + #{route.title}", route
      %br
      %strong= route.difficulty

app/views/routes/_search_form.html.haml
= semantic_form_for Route.new, :url => "/filter", :remote => true, :method => :get, :html => { :class => 'form-horizontal' } do |f|
  = f.select :continent_id, options_from_collection_for_select(Continent.all, 'id', 'title'), :include_blank => true
  = f.select :region_id, options_from_collection_for_select(Region.all, 'id', 'title'), :include_blank => true
  = f.select :mount_id, options_from_collection_for_select(Mount.all, 'id', 'title'), :include_blank => true
  = submit_tag "Search", :class => 'btn btn-primary'

app/views/routes/edit.html.haml
- model_class = Route
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/routes/filter.html.haml
= render partial: "routes_list", :locals => {routes: @routes}

app/views/routes/filter.js.erb
$('table.table-striped').html()
$('table.table-striped').html("<%= escape_javascript(render partial: "routes_list", :locals => {routes: @routes}) %>")

app/views/routes/index.html.haml
.page-header

= render "search_form"
= render partial: "routes_list", :locals => {routes: @routes}

app/views/routes/new.html.haml
- model_class = Route
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/routes/show.html.haml
%h1="#{@route.mount.title} + #{@route.title}"
- if can? :edit, @route
  = link_to "Редактировать", edit_route_path(@route) 
%p  
  %strong= "Сложность: #{@route.difficulty}"
  %br
  = image_tag @route.photo.url

%h3= "Описание."
%p= @route.description